### ISSUE TITLE
Some conflict with  Helix‘s Yazuza 3D Vision Fix

### ISSUE THREAD

**Issue by maierxiaqu** [ibldzn/yakuza-0-legend-style-fix#1]
This will conflict Helix‘s Yazuza 3D Vision Fix , when with 3D Vision Fix game will not launch.

**Comment by ibldzn** [comment]
must've been because I only exported the functions the game needs, I'll fix it in the next update! 

thanks for reporting the issue

**Comment by ibldzn** [comment]
@maierxiaqu can you test [this](https://drive.google.com/file/d/1UZIKH0Jq1OGKFREktqlpOlV4ay2XtfEg/view?usp=sharing) for me? I'll push the update after you said it's okay.

I can't test it because it keeps crashing on my machine (probably because I have amd card and that mod uses nvidia api dll)

rename your "libtgsa.dll" to "libtgsa_o.dll" then paste the file in. ![Screenshot](https://i.imgur.com/feeQ0Va.png)

**Comment by maierxiaqu** [comment]
Unfortunately it still crash the game, so I don't think it's  concern about the graphic card.
![捕获](https://user-images.githubusercontent.com/56471006/106359209-7cf89280-6354-11eb-8f72-9a738f0a01c5.JPG)

**Comment by ibldzn** [comment]
if that "dxgi.dll" is from here try to delete it first then launch the game.

**Comment by maierxiaqu** [comment]
After deleted no more conflict, probably some file was incompatible with dxgi.dll
