### ISSUE TITLE
beating the cabaret club quest line made Majima permamently stuck in Legend style.

### ISSUE THREAD

**Issue by nwngdngl** [ibldzn/yakuza-0-legend-style-fix#15]
as soon as the style change animation plays out Majima will automatically switch to Mad Dog, disabling Mad Dog in the pause menu results in nothing (Majima will still change to Mad Dog once I unpause).

EDIT: okay, I managed to get it unstuck via a breaker battle, but still this might be an issue worth looking into.

2nd EDIT: okay, no, the issue pops back up later after a while, idk what to do to fix it permamently.

**Comment by ibldzn** [comment]
> beating the cabaret club quest line

as in completing the whole quest line to unlock the legend style or just playing the cabaret with legend style already unlocked? it's been ages since the last time i played the game but aren't you supposed to complete the cabaret quest line to unlock the legend style?

i don't think the later is possible because this mod won't do anything unless you're in a fight, but feel free to post more detail

**Comment by nwngdngl** [comment]
this is my 2nd playthrough of the game, I forget what I exactly did, I'm pretty sure I hexedited the save file to have the Legend styles unlocked using an instruction someone posted on Steam forums.

I'll dig that page up after work and see if in my save file the 1 for "Legend styles unlocked" is a 2 or something like that and see if I can fix it that way.

**Comment by nwngdngl** [comment]
okay, so I figured it out - the trainer I was using to speed past the cutscenes was causing the style fuckup. not sure why, but that is the culprit.
